### ISSUE TITLE
virtual_screening_pipeline.ipynb cannot be properly displayed.

### ISSUE THREAD

**Issue by maskot1977** [grisoniFr/scaffold_hopping_whales#1]
Hello, I am interested in this new descriptors. However, virtual_screening_pipeline.ipynb cannot be properly displayed. 

<img width="978" alt="Screenshot 0003-04-22 12 53 17" src="https://user-images.githubusercontent.com/2269618/115653210-b811cd00-a369-11eb-8219-19e27b0cab13.png">

Would you please kindly fix this?

**Comment by grisoniFr** [comment]
Hello,

this is not an issue of the Jupyter notebook file but of the GitHub notebook renderer (https://github.com/jupyter/notebook/issues/5323). 

if you clone the repository locally, launch Jupyter notebook and then open the .ipynb file from there, everything will be displayed correctly. 

How to do so is explained in the README file. Also, a step-by-step guide can be found here: https://link.springer.com/protocol/10.1007%2F978-1-0716-1209-5_2

**Comment by maskot1977** [comment]
Resolved. Thank you very much!
